title: July Web Page
subtitle: Personal site
description: >- # this means to ignore newlines until "baseurl:"
  Personal site of Julio Martin (a.k.a. July)
url: "https://julymaker.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

### Multi-Languag variable
languages: ["es", "en"]
default_lang: "es"
exclude_from_localizations: ["assets", "gallery", "_sass"]

urls:
    - text: about
      url: /about
    #- text: Blog
    #  url: /blog
    #- text: Gallery
    #  url: /gallery
    #- text: Shop
    #  url : /shop
    - text: contact
      url : /contact
    #- text: Styleguide
    #  url: /styleguide
    #- text: Get Started
    #  url: /get-started

# Edit these details

author_logo: profile.webp
about_logo: profile2.webp
author: Julio Martin
author_name: Julio
author_lastname: Martin
author_email: "julio.martin.saez@gmail.com"
author_location: Madrid
author_website_url: "http://julymaker.github.com"

# Typewrite config
typewrite_htmlId: input-typewrite
typewrite_typeSpeed: 50
typewrite_backSpeed: 10
typewrite_backDelay: 5000
typewrite_startDelay: 200
typewrite_shuffle: true
typewrite_loop: true
typewrite_loopCount: Infinity
typewrite_cursorChar: '|'


author_work_experiences:
            - company_name: Dassault Systemes
              company_logo: DS_128x128.webp
              company_url: https://www.3ds.com/
              visibility: true
            - company_name: Next Limit
              company_logo: nextlimit.webp
              company_url: https://nextlimit.com
              visibility: true
            - company_name: Human Brain Project
              company_logo: HP_128x128.webp
              company_url: https://www.humanbrainproject.eu
              visibility: true
            - company_name: Compusoft
              company_logo: compusoft_128x128.webp
              company_url: https://www.compusof.com/
              visibility: true

author_education_details:
              - college_logo: urjc.webp
                college_id: URJCMaster
                college_name: URJC
                college_url: https://urjc.es
                visibility: true
              - college_logo: urjc.webp
                college_id: URJCGrado
                college_name: URJC
                college_url: https://urjc.es
                visibility: true

                
# author_project_details:
#               - project_thumbnail: gamershub.png
#                 project_title: Gamers Hub
#                 project_description: A Platform built for Gamers and Game Devs
#                 project_url: https://gamershub.in
#                 visibility: true
#               - project_thumbnail: hack4r.PNG
#                 project_title: Hack4r
#                 project_description: A Platform built for Hackers and Penetration Testers
#                 project_url: https://hack4r.com
#                 visibility: true

# social links
twitter_username: JulioMartinSaez
github_username:  JulyMaker
facebook_username: null
linkedin_username: julio-martin-saez
behance_username: null
instagram_username: j.u.l.y.maker
medium_username: null
telegram_username: null
dribbble_username: null
flickr_username: null
spotify_username: null
spotify_playlist: 1PbDnV1w31gf9blJcYxpWV

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: July

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: xknqbzla

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-169279340-1

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# algolia search
#algolia:
#  application_id: D9WA1YKTRQ
#  index_name: blog_posts # You can replace that with whatever name you want
#  files_to_exclude: []
#  nodes_to_index: 'article'
#  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
collections:
 - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
 # - jekyll-algolia
  - jekyll-menus
  - jekyll-multiple-languages-plugin


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build